#!/bin/sh

# Install script for Nobara splashscreen
# Version 1.0


# Check if the script is executed with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root. Please use sudo or execute as root user."
  exit 1
fi


# Check if user is running KDE Plasma
if pgrep -x "ksmserver" > /dev/null; then
    #echo "KDE Plasma is."
    true
else
    echo "System is not running KDE Plasma. Skip install."
    exit 1
fi


# Check if Plasma Appearance folder exists
FOLDER_PATH="/home/$(logname)/.local/share/plasma"
if [ ! -d "$FOLDER_PATH" ]; then
    # If the folder does not exist, create it
    mkdir -p "$FOLDER_PATH"
    echo "Folder missing, created: $FOLDER_PATH"
fi

FOLDER_PATH="/home/$(logname)/.local/share/plasma/look-and-feel"
if [ ! -d "$FOLDER_PATH" ]; then
    # If the folder does not exist, create it
    mkdir -p "$FOLDER_PATH"
    echo "Folder missing, created: $FOLDER_PATH"
fi


# Copy splashscreen folder over
FOLDER_PATH="/home/$(logname)/.local/share/plasma/look-and-feel/"
SPLASH_FOLDER="${PWD}/Nobara.SplashScreen/"
echo "${PWD}/Nobara\.SplashScreen/"
cp -rv "$SPLASH_FOLDER" "$FOLDER_PATH"


echo -e "\nSplashscreen install successful"
exit 0
