#!/bin/bash

# Packing script for Nobara splashscreen, used to create tar to be uploaded online for download
# Version 1.1

source "$PWD/env"

# Check if tar utility exist on system
if command -v tar &> /dev/null; then
    echo -e "Start packing... \n"
else
    echo "tar utility is not installed. Skip packing."
    exit 1
fi

# Create temp Folder
mkdir -v ${PWD}/${SPLASH_ID}

# Copy splashscreen content to temp folder
cp -rp "${PWD}/${SPLASH_ID}" ${PWD}/packtemp
cp -vp ${PWD}/install ${PWD}/packtemp

# Archive the folder
tar -cvf ${SPLASH_ID}.tar packtemp &&

# Delete temp Folder
rm -rf "${PWD}/packtemp/"

# Complete packing
echo -e "\nPacking complete! The tar file should be in the project root folder."
exit 0
